name: flutter_spareparts_store
description: A new Flutter setup application for starting a project.

publish_to: 'none'
version: 2.0.10+10
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get_it: ^8.0.3
  provider: ^6.0.3
  connectivity_plus: ^3.0.6
  dio: ^5.3.4
  http: ^1.1.1
  shared_preferences: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.0.2
  image_picker: ^1.0.4
  webview_flutter: ^4.4.2
  flutter_html: ^3.0.0-alpha.3
  share_plus: ^7.2.1
  photo_view: ^0.15.0
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_auth: ^5.3.1
  wakelock_plus: ^1.3.2
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.0.1
  google_sign_in: ^6.1.6
  flutter_svg: ^2.0.9
  phone_number: ^2.0.1
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.5.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  flutter_typeahead: ^5.2.0
  marquee: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_widget_from_html: ^0.15.3
  flutter_widget_from_html_core: ^0.15.2
  flutter_html_table: ^3.0.0-alpha.3
  fluttertoast: ^8.0.9
  permission_handler: ^11.1.0
  flutter_downloader: ^1.8.0+1
  country_currency_pickers: ^3.0.0
  dropdown_search: ^5.0.3
  flutter_inappwebview: ^6.0.0
  path: ^1.8.2
  cached_network_image: ^3.3.0
  http_parser: ^4.0.2
  intl: ^0.19.0
  sign_in_with_apple: ^5.0.0
  expandable_bottom_sheet: ^1.1.1+1
  dotted_border: ^2.0.0+3
  dotted_line: ^3.2.2
  flutter_slidable: ^3.0.0
  percent_indicator: ^4.2.3
  just_the_tooltip: ^0.0.12
  substring_highlight: ^1.0.33
  card_swiper: ^3.0.1
  flutter_native_splash: ^2.3.2
  animations: ^2.0.8
  emoji_picker_flutter: ^1.6.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  sqflite: 2.2.7
  just_audio: ^0.9.36
  file_picker: ^8.1.4
  external_app_launcher: ^4.0.0
  mobile_scanner: ^7.0.0
  simple_barcode_scanner: ^0.1.1
  data_filters: ^1.0.2
  nfc_manager: ^3.5.0
  get: ^4.6.5
  timelines: ^0.1.0
  flutter_switch: ^0.3.2
  shimmer_animation: ^2.1.0+1
  fl_chart: ^0.69.2
  printing: ^5.11.0
  syncfusion_flutter_datepicker: ^28.1.35
  multi_select_flutter: ^4.1.3
  youtube_player_flutter: ^9.0.4
  table_calendar: ^3.0.9
  model_viewer_plus: ^1.7.2
  flutter_3d_controller: ^2.0.2
  url_strategy: ^0.3.0
  flutter_cached_pdfview: ^0.4.3
  easy_pdf_viewer: ^1.0.8
  pdfrx: ^1.0.94
  side_sheet: ^1.0.4




dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/images/gltf/
    - assets/images/threed/
    - assets/images/task/

  fonts:
    - family: SF-Pro-Rounded-Regular
      fonts:
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 600
